# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  build-frontend:
    name: "Build CodersCamp Organization App Frontend"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: CI=false npm run build --if-present # CI=true npm run build --if-present if you want to treat warnings as errors in deployment
      - run: CI=false npm test # same as above, prepend CI=true to treat warning as errors
      - run: ls ./
      - uses: actions/upload-artifact@v1
        name: Upload build as artifact
        if: always()
        with:
          name: frontend-dist
          path: ./build
  deploy-frontend-on-github-pages:
    name: "Deploy app to GitHub Pages from main branch source code"
    if: github.ref == 'refs/heads/master'
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: frontend-dist
          path: ./build
      - name: Deploy app as GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.0-6
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          publish_dir: "./build"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true
          keep_files: true